substitutions:
  device_name: "guest-room-panel"
  friendly_name: Guest room - Panel
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

packages:
  #core:               !include packages/Blackymas/esphome/nspanel_esphome_core.yaml
  #standard:           !include packages/Blackymas/esphome/nspanel_esphome_standard.yaml
  #nspanel_package:    !include packages/Blackymas/nspanel_esphome.yaml
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    refresh: 300s
    files:
      - nspanel_esphome.yaml # Base package including TFT transfer
      # - esphome/nspanel_esphome_addon_bluetooth_proxy.yaml
  wifi: !include packages/config_wifi.yaml

  manual_ip: !include
    file: packages/config_manual_ip.yaml
    vars:
      ip: !secret ip_guest_room_panel

#bluetooth_proxy:

#esp32:
#  framework:
#    type: arduino

#logger:
#  level: VERBOSE
#  logs:
#    bluetooth_proxy: debug
#    esp-idf: info

#factory_reset:
#  resets_required: 5
#  max_delay: 10s
